export const actionTypes = {
  CHANGE_PASSWORD_NOT_EMPTY: "CHANGE_PASSWORD_NOT_EMPTY" as string,
  CHANGE_PASSWORD: "CHANGE_PASSWORD" as string,
  ERROR_CHECK_USERACCOUNT: "ERROR_CHECK_USERACCOUNT" as string,
};
