export const actionTypes = {
  CHECKED_CREDIENTIALS_NOT_EMPTY: "CHECKED_CREDIENTIALS_NOT_EMPTY" as string,
  CHECKED_PASSWORD: "CHECK_PASSWORD" as string,
  ERROR_CHECK_EMAIL: "ERROR_CHECK_EMAIL" as string,
  ERROR_CHECK_PASSWORD: "ERROR_CHECK_PASSWORD" as string,
};
